### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jamesnyakush** [waynegakuo/larampesa#1]
You can use the following packages 
1. [laravel mpesa](https://github.com/gathuku/laravel_mpesa) 
2. [Smodav mpesa](https://github.com/SmoDav/mpesa)
3. [smodav implementation](https://github.com/SmoDav/mpesa-implementation)

its been long since I last used packages in laravel and some of the packages are not maintained like smodav. Otherwise, package free will help u have an upgrade compatibility version wise. 
willing to contribute

**Comment by waynegakuo** [comment]
Thank you bro. I will be using `laravel mpesa` package for this.
Thank you once again for the referral
